version: "3.3"

volumes:
  db_data:

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env-docker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build:
      context: .
    env_file:
      - .env-docker
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["/flask_app/app.sh"]

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 1234
